services:
  frontend:
    image: molndal/azure_tenta-frontend
    ports:
      - 8081:80
    volumes:
      - ./frontend/index.html:/usr/share/nginx/html/index.html  # Mounts frontend volume for static files
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Mount NGINX config
    depends_on:
      - backend

  backend:
    build: ./backend  # Build backend from Dockerfile
    environment:
      MONGO_URI: mongodb://mongo:27017/commentsdb  # MongoDB connection URI
    depends_on:
      - mongo

  mongo:
    image: molndal/azure_tenta-mongodb
    volumes:
      - mongo_data:/data/db  # Volume for MongoDB data persistence

volumes:
  mongo_data:
  frontend:
